# RelayPoint Elite - Pre-commit Configuration
# See https://pre-commit.com for more information

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: check-case-conflict

# Python code formatting and linting
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        language_version: python3.11

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.5
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-PyYAML, pydantic]
        exclude: ^(tests/|docs/)

# JavaScript/TypeScript code formatting and linting
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, yaml]
        exclude: ^(dist/|build/|node_modules/)

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.54.0
    hooks:
    -   id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
        -   eslint@8.54.0
        -   eslint-plugin-react@7.33.2
        -   eslint-plugin-react-hooks@4.6.0
        -   eslint-config-prettier@9.0.0
        -   eslint-plugin-prettier@5.0.1
        -   prettier@3.1.0
        -   typescript@5.3.3
        -   '@typescript-eslint/eslint-plugin@6.13.1'
        -   '@typescript-eslint/parser@6.13.1'
        exclude: ^(dist/|build/|node_modules/)

# Docker linting
-   repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
    -   id: hadolint
        files: Dockerfile.*

# Security scanning
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
        exclude: ^(tests/|docs/)

# Kubernetes manifest validation
-   repo: https://github.com/instrumenta/kubeval
    rev: v0.16.1
    hooks:
    -   id: kubeval
        files: k8s/.*\.yaml$
        exclude: ^(k8s/templates/)