apiVersion: v2
name: relaypoint
description: A Helm chart for RelayPoint Elite - Enterprise Workflow Automation Platform
type: application
version: 0.1.0
appVersion: "2.0.0"
keywords:
  - workflow
  - automation
  - fastapi
  - react
maintainers:
  - name: RelayPoint Team
    email: demond.balentine@atlasstudents.com
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled